### ISSUE TITLE
INVALID_SESSION_ID: Session expired or invalid

### ISSUE THREAD

**Issue by Nithesh1501** [Nisar-99/Lightning-Studio#10]
Hi 
Seeing this error when I open the Lightning studio only on Opera Browser. But works fine with chrome
 
![image_2024-10-28_223828353](https://github.com/user-attachments/assets/e1baa67c-3972-439e-8935-c88cbcb13cb5)

**Comment by Nisar-99** [comment]
Fixed: Please update the latest version 3.0.8. Thank you
