### ISSUE TITLE
Invalid reference for fields that exist in org custom object

### ISSUE THREAD

**Issue by smo17** [Nisar-99/Lightning-Studio#11]
If LWC js file imports existing fields from a custom object, some fields are not recognized.

Snippet of LWC  :
```
import { LightningElement, wire } from 'lwc';
import { getRecord, getFieldValue } from 'lightning/uiRecordApi';

import BOAT_PICTURE_FIELD from "@salesforce/schema/Boat__c.Picture__c";
import BOAT_NAME_FIELD from "@salesforce/schema/Boat__c.Name";
import BOAT_OWNER_FIELD from "@salesforce/schema/Boat__c.Contact__r.Name";
import BOAT_PRICE_FIELD from "@salesforce/schema/Boat__c.Price__c";
import BOAT_TYPE_FIELD from "@salesforce/schema/Boat__c.BoatType__r.Name";

const BOAT_FIELDS = [BOAT_PICTURE_FIELD, BOAT_NAME_FIELD,BOAT_OWNER_FIELD, BOAT_PRICE_FIELD, BOAT_TYPE_FIELD];

export default class Boats extends LightningElement {
    
    
    boatId;
    get showBoat() {
        return this.boatId != null;
    }
.....

```
Error message received when saving code to org:
Invalid reference Boat__c.BoatType__r.Name of type sobjectClass in file boatPicker.js: Source
Invalid reference Boat__c.Picture__c of type sobjectField in file boatPicker.js: Source	
Invalid reference Boat__c.Contact__r.Name of type sobjectClass in file boatPicker.js: Source
Invalid reference Boat__c.Price__c of type sobjectField in file boatPicker.js: Source

**Comment by Nisar-99** [comment]
Please deploy with using standard deployment mode.
![image](https://github.com/user-attachments/assets/1454c4c1-86ae-4be4-8591-deb990d02e41)

**Comment by smo17** [comment]
it works, thanks for building this tool 🥇
