### ISSUE TITLE
FIELD_INTEGRITY_EXCEPTION while creating new CSS file in LWC

### ISSUE THREAD

**Issue by sacsha30** [Nisar-99/Lightning-Studio#6]
I am trying to create a new CSS file in my LWC but it is throwing error FIELD_INTEGRITY_EXCEPTION. I have checked the Standard Salesforce Deployment? field but no luck.

**Comment by Nisar-99** [comment]
Fixed: Please update to version 3.0.8 and deploy the components using the standard deployment mode if you encounter a FIELD_INTEGRITY_EXCEPTION.
